---
- name: test connection
  ping:
- name: install openjdk-8-jdk
  apt:
    name: openjdk-8-jdk
    update_cache: yes
- name: create nexus user
  user:
    name: nexus
- name: create nexus directory
  file:
    state: directory
    path: /opt/nexus
- name: download nexus
  unarchive:
    creates: /opt/nexus/nexus-3.15.2-01/bin/nexus
    dest: /opt/nexus
    remote_src: yes
    src: http://download.sonatype.com/nexus/3/nexus-3.15.2-01-unix.tar.gz
- name: change ownership of directory  
  file:
    state: directory
    path: /opt/nexus
    owner: nexus
    recurse: yes
- name: give access to user nexus
  lineinfile:
    create: yes
    path: /opt/nexus/nexus-3.15.2-01/bin/nexus.rc
    line: run_as_user="nexus"
- name: create symbolic link
  file:
    state: link
    path: /etc/init.d/nexus
    src: /opt/nexus/nexus-3.15.2-01/bin/nexus
- name: start nexus
  systemd:
    daemon_reload: yes
    name: nexus
    state: started
